import Navbar from "@/components/navbar";
import { QueryLayout } from "@/components/QueryLayout";
import type { Metadata } from "next";
import { getLocale } from "next-intl/server";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-100 antialiased`}>
        <div className="mx-auto flex max-w-2xl flex-col gap-8">
          <QueryLayout locale={locale}>
            <Navbar />
            {children}
          </QueryLayout>
        </div>
      </body>
    </html>
  );
}
